### ISSUE TITLE
Webhook failes on K8S 1.22++

### ISSUE THREAD

**Issue by robert-heinzmann-logmein** [anchore/kubernetes-admission-controller#45]
The webhook controller failes to start on k8s 1.22++ as the ValidatingWebHook is v1beta1 is now removed

```
democtl-anchore-admission-controller-d9b454d5f-b4kdv      0/1     Running   0             7m26s
```

Log:
```
E0213 11:36:27.463870       1 webhook.go:196] Failed to make webhook authorizer request: the server could not find the requested resource
E0213 11:36:27.464009       1 errors.go:77] the server could not find the requested resource
I0213 11:36:27.464043       1 wrap.go:47] GET /healthz: (5.147022ms) 500
goroutine 288 [running]:
k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc000276fc0, 0x1f4)
        /go/pkg/mod/k8s.io/apiserver@v0.0.0-20190313205120-8b27c41bdbb1/pkg/server/httplog/httplog.go:204 +0xc8
k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc000276fc0, 0x1f4)
        /go/pkg/mod/k8s.io/apiserver@v0.0.0-20190313205120-8b27c41bdbb1/pkg/server/httplog/httplog.go:183 +0x35
k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc00000db60, 0x1f4)
        /go/pkg/mod/k8s.io/apiserver@v0.0.0-20190313205120-8b27c41bdbb1/pkg/server/filters/timeout.go:205 +0xb2
net/http.Error(0x7ff7af1c07a0, 0xc00000e0a8, 0xc000047800, 0x53, 0x1f4)
        /usr/local/go/src/net/http/server.go:2048 +0x1f4
k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.InternalError(0x7ff7af1c07a0, 0xc00000e0a8, 0xc000262600, 0x1b877c0, 0xc000590140)
        /go/pkg/mod/k8s.io/apiserver@v0.0.0-20190313205120-8b27c41bdbb1/pkg/endpoints/handlers/responsewriters/errors.go:75 +0x11a
k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7ff7af1c07a0, 0xc00000e0a8, 0xc000262600)
        /go/pkg/mod/k8s.io/apiserver@v0.0.0-20190313205120-8b27c41bdbb1/pkg/endpoints/filters/authorization.go:69 +0x432
net/http.HandlerFunc.ServeHTTP(0xc00020a700, 0x7ff7af1c07a0, 0xc00000e0a8, 0xc000262600)
        /usr/local/go/src/net/http/server.go:2036 +0x44
k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7ff7af1c07a0, 0xc00000e0a8, 0xc000262600)
        /go/pkg/mod/k8s.io/apiserver@v0.0.0-20190313205120-8b27c41bdbb1/pkg/server/filters/maxinflight.go:160 +0x5e3
net/http.HandlerFunc.ServeHTTP(0xc00052ab40, 0x7ff7af1c07a0, 0xc00000e0a8, 0xc000262600)
        /usr/local/go/src/net/http/server.go:2036 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7ff7af1c07a0, 0xc00000e0a8, 0xc000262600)
        /go/pkg/mod/k8s.io/apiserver@v0.0.0-20190313205120-8b27c41bdbb1/pkg/endpoints/filters/impersonation.go:50 +0x1eff
net/http.HandlerFunc.ServeHTTP(0xc00020a780, 0x7ff7af1c07a0, 0xc00000e0a8, 0xc000262600)
        /usr/local/go/src/net/http/server.go:2036 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7ff7af1c07a0, 0xc00000e0a8, 0xc000262500)
        /go/pkg/mod/k8s.io/apiserver@v0.0.0-20190313205120-8b27c41bdbb1/pkg/endpoints/filters/authentication.go:81 +0x554
net/http.HandlerFunc.ServeHTTP(0xc000252c30, 0x7ff7af1c07a0, 0xc00000e0a8, 0xc000262500)
        /usr/local/go/src/net/http/server.go:2036 +0x44
k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc000047680, 0xc00030b300, 0x1bca900, 0xc00000e0a8, 0xc000262500)
        /go/pkg/mod/k8s.io/apiserver@v0.0.0-20190313205120-8b27c41bdbb1/pkg/server/filters/timeout.go:108 +0xd0
created by k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
        /go/pkg/mod/k8s.io/apiserver@v0.0.0-20190313205120-8b27c41bdbb1/pkg/server/filters/timeout.go:97 +0x1b0

logging error output: "Internal Server Error: \"/healthz\": the server could not find the requested resource\n"
 [kube-probe/1.22 100.96.1.1:42180]
```

**Comment by robert-heinzmann-logmein** [comment]
This is most likely https://kubernetes.io/docs/reference/using-api/deprecation-guide/#apiservice-v122

**Comment by pbalogh-sa** [comment]
@robert-heinzmann-logmein  Thanks for reporting this. We will fix it soon.

**Comment by robert-heinzmann-logmein** [comment]
Any news on this topic ?

**Comment by zhill** [comment]
@robert-heinzmann-logmein thanks for the great writeup and I'm looking at this now. We definitely intend this to work for all new k8s releases. I'll use this issue to track changes. It looks like we'll have to take a different approach to handling the API routing as the underlying library this uses for the controller framework isn't maintained or updated for newer k8s releases.
